<a href="https://colab.research.google.com/github/ronaksainiwork-droid/Student_data/blob/main/Advancepython_ronak.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Python Notes

**NUMPY**




In [ ]:
# Introduction to Numpy --->
# Numpy ---> NUm ( Numerical) + Py(Python)

# This is an open - source Library of python and this is used for scientific Calculation .
# List is Hetrogeneous Data type and Numpy is Homogeneous Data Type .



In [ ]:
a = [1,2,3]
a*3


[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a*3

array([3, 6, 9])

In [ ]:
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

In [ ]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Row = 3 ,r_1 = [1,2,3] , r_2 = [4,5,6] , r_3 = [7,8,9]
# Column = 3 , C_1 = [1,4,7] , C_2 = [2,5,8] , C_3 = [3,6,9]

In [ ]:
print("total Shape " , b.shape)     ### Shape = row , column
print("total Dimension " , b.ndim)  ### size = row*column
print("total Elements " , b.size)   ### total dimension = 2

total Shape  (3, 3)
total Dimension  2
total Elements  9


In [ ]:
## Pre-defined Functions in Numpy

In [ ]:
 # (1). zeros() ----> It will create an array in which all the values will be 0 in either
 # one Dimensional or multi-dimensional .
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# (2) one() ---> It will return an array in which all the values are 1 in either
# one Dimension or multi-dimension

a = np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

  ###  Date 5 march


In [ ]:
# (3). eye() ----> It will create an array in which digonal positional elements are 1 and rest all
# are 0.

In [ ]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# (4). diag() ----> It will set our custm values on digonal position .
a = np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [ ]:
b = np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [ ]:
# (5). Random Module
# (a). Randint() ---> It will create random numbers in a given range .
# sytax: np.random.randint(min_range , max_range , total_numbers)

In [ ]:
a = np.random.randint(1,10,3)
a

array([5, 1, 9])

In [ ]:
# (b). Rand() ---> It will create random numbers in range 0-1/

In [ ]:
a = np.random.rand(5)
a

array([0.65658716, 0.79587397, 0.92556744, 0.09064025, 0.52061495])

In [ ]:
# (c). seed() ----> It will fix our random generated data .

In [ ]:
np.random.seed(3)
a = np.random.randint(1,10,3)
a

array([9, 4, 9])

In [ ]:
# View Vs Copy

# View means modification in original data and copy means changes in duplicate data will not reflect
# the original data .

In [ ]:
a = np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
a[3:6] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [ ]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
b

array([0, 0, 0])

In [ ]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# Operation on Array

In [ ]:
# (1). arange() -----> It will works as as for loop in numpy .

In [ ]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
b = a%2== 0

In [ ]:
# Reshaping condition
# n(rows) * n(columns) = n(total_elements)

In [ ]:
  # total ememtns = 12
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 , 4*3


In [ ]:
a = np.random.randint(1,50,12)
a

array([ 9,  1, 22, 20, 11, 44, 42, 11, 22, 39, 33, 21])

In [ ]:
a.reshape(2,6)

array([[ 9,  1, 22, 20, 11, 44],
       [42, 11, 22, 39, 33, 21]])

In [ ]:
a.reshape(3,4)

array([[ 9,  1, 22, 20],
       [11, 44, 42, 11],
       [22, 39, 33, 21]])

In [ ]:
# a.reshape(3,5)

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b   ### Not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b)   ### Matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

Date 6 march

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
## for matrix Multiplication
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
a**3

array([ 1,  8, 27, 64])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# LinSpace() ----> It will return same gap values in a given range .

In [ ]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
 # Unique() ----> It will return 3 arrays .
# arr ---> return original values of array .
# return_index = True ----> return return index value of unqie numbers .
# return_counts = True ----> It will return total freqnecy of each unique value .

In [ ]:
a = np.array([1,2,3,2,2,2,3,3,2,4,5])
a

array([1, 2, 3, 2, 2, 2, 3, 3, 2, 4, 5])

In [ ]:
np.unique(a , return_index=True , return_counts=True)

(array([1, 2, 3, 4, 5]), array([ 0,  1,  2,  9, 10]), array([1, 5, 3, 1, 1]))

In [ ]:
# hstack() and vstack()

# hstack() ----> It will add 2 or more arrays in horizontally .
# vstack() ----> It will add 2 or more arrays in vertically.

In [ ]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
c = np.arange(9,13).reshape(2,2)


In [ ]:
np.hstack((a,b,c))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# question
  # array (30,80) total elements 36 ---> reshape (2*18, 4*9,6*6)

# array ----> [6,10], [11,15] ---> conbined horizontally



# parctise numpt

# Pandas
10 march

In [ ]:
# Pandas ----> Pandas is an open-source library which is used for handle data manipulations.

In [ ]:
import pandas as pd

In [ ]:
# Data Structure of Pandas :::::
# (1). Series  ----> It stores only values not column name and it is one-dimensional.
# (2). DataFrame ---> It store values with column name. And it is multi-dimensional.

In [ ]:
a = pd.Series([1,45,78,90])
# a

In [ ]:
  # type(a)

In [ ]:
### DataFrame

In [ ]:
b = {
    "Emp_ID": [1,2,3,4,5],
    "Name": ['Sam','Mohit','Raj','Rahul','Aniket'],
    "Department": ['IT','Sales','IT','IT','Sales'],
    "Salary": [20000,25000,30000,31000,26000]
}

In [ ]:
type(b)

dict

In [ ]:
df = pd.DataFrame(b)
df

,Emp_ID,Name,Department,Salary
0,1,Sam,IT,20000
1,2,Mohit,Sales,25000
2,3,Raj,IT,30000
3,4,Rahul,IT,31000
4,5,Aniket,Sales,26000


In [ ]:
### Export this data into csv

In [ ]:
df.to_csv("Emp_data.csv")

In [ ]:
### Export this data into Excel

In [ ]:
df.to_excel("New_Emp_data.xlsx")

In [ ]:
#### Import the data

In [ ]:
a = pd.read_csv("/content/Emp_data.csv")
# a

In [ ]:
###  import phone data

In [ ]:
b = pd.read_csv("/content/Latest Phone list.csv")
b

FileNotFoundError: [Errno 2] No such file or directory: '/content/Latest Phone list.csv'

Date 11 March

In [ ]:
## Asignment in class

In [ ]:
import pandas as pd

In [ ]:
b = {
    "std_id" : [1,2,3,4,5,6,7,8,9,10],
    "std_name" : ['Ronak','Mohit','Raj','Rahul','Aniket' , 'rohit' , 'Aman' , 'Aabid' , 'Nayum' , 'Rahul' ],
    "C_name" : ['D. Science' , 'D.  Eng. ', 'M. Stack', 'Full stack' , 'D. Science' , 'D. Eng.', 'M.Stack' , 'D.science' , 'D.Marketing' , 'D.Science'],
    "C_Duration (Months)" : [10,8,8,12,10,8,8,10,4,10],
    "C_fees (K)" : [60,55,50,50,60,55,50,60,45,60],

}

In [ ]:
df = pd.DataFrame(b)
df

,std_id,std_name,C_name,C_Duration (Months),C_fees (K)
0,1,Ronak,D. Science,10,60
1,2,Mohit,D. Eng.,8,55
2,3,Raj,M. Stack,8,50
3,4,Rahul,Full stack,12,50
4,5,Aniket,D. Science,10,60
5,6,rohit,D. Eng.,8,55
6,7,Aman,M.Stack,8,50
7,8,Aabid,D.science,10,60
8,9,Nayum,D.Marketing,4,45
9,10,Rahul,D.Science,10,60


In [ ]:
# exportr in .csv
df.to_csv("Std_data.csv")



In [ ]:
# export in xlsx file
df.to_excel("Std_data.xlsx")


In [ ]:
# Import csv file

In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv("/content/hotels_dataset.csv")
a

,Hotels Names,price (Details),Price,Hotel Star,Facilities,Extra Facilities,Parkings,Fitness Facilities
0,JW Marriott Mussoorie Walnut Grove Resort & Spa,1 night with taxes + fees1,"₹11,685 total",5-star hotel,Free breakfast,Free Wi-Fi,Free parking,Fitness centre
1,"Welcomhotel By ITC Hotels, The Savoy, Mussoorie",1 night with taxes + fees,"₹12,198 total",5-star hotel,Free breakfast,Wi-Fi,Free parking,Fitness centre
2,"Rokeby Manor, Mussoorie",1 night with taxes + fees,"₹21,274 total",4-star hotel,Free breakfast,Wi-Fi,Free parking,Spa
3,Set your dates to update prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ramada By Wyndham Mussoorie Mall Road,1 night with taxes + fees,"₹11,685 total",4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Bar
5,Jaypee Residency Manor,1 night with taxes + fees,"₹12,198 total",5-star hotel,Free breakfast,Free Wi-Fi,Free parking,Air conditioning
6,Renest Dunsvirk Court Mussoorie,1 night with taxes + fees,"₹5,711 total",4-star hotel,Free breakfast,Wi-Fi,Parking,Spa
7,"Fortune Resort Grace Mussoorie, Uttarakhand - ...",1 night with taxes + fees,"₹18,879 total",4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Spa
8,"jüSTa Hollow Oak, Mussoorie",1 night with taxes + fees,"₹13,225 total",4-star hotel,Free breakfast,Wi-Fi,Parking,Kitchen in some rooms
9,"Tree of Life Highlands, Mussoorie",NaN,NaN,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Room service


# 12/03/25 (pandas)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/covid_toy - covid_toy.csv")
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [ ]:
### head()
### Top data check , we will use df.head() , by default it returns top 5 rows.
df.head(2)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes


In [ ]:
## tail()
### bottom data check, we will use df.tail() , by default it returns last rows.
df.tail(3)

,age,gender,fever,cough,city,has_covid
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No
99,10,Female,98.0,Strong,Kolkata,Yes


In [ ]:
## sample()
### If you want random indexed data , then we will use df.sample(). By default it will
### returns single row.
df.sample()

,age,gender,fever,cough,city,has_covid
18,64,Female,98.0,Mild,Bangalore,Yes


In [ ]:
### If we want to check data type of each column. df.dtyps
df.dtypes

,0
age,int64
gender,object
fever,float64
cough,object
city,object
has_covid,object


In [ ]:
## info()
### If we want to check overall information then we will use df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [ ]:
## describe()
## If you want t0 check statical view of data , then you can use df.describe()
df.describe()

,age,fever
count,100.000000,90.000000
mean,44.220000,100.844444
std,24.878931,2.054926
min,5.000000,98.000000
25%,20.000000,99.000000
50%,45.000000,101.000000
75%,66.500000,102.750000
max,84.000000,104.000000


In [ ]:
df.head(2)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes


In [ ]:
## isnull().sum()
### If you want to check missing data in df , then you will use df .isnull().sum()

In [ ]:
df.isnull().sum()   ### here fever has 10 missing values.

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [ ]:
# x = 1 , 2,3 NaN , 5
# mean = (1+2+3+4+5)/4 = 11/4 = 2.75
# we will fill this value in this missing data.
# x =

In [ ]:
## .fillna -->
#  we want to replace NaN (missing) values
# ( Mean Imputation (missing values fill using mean )

x=df['fever'] =df['fever'].fillna(df['fever'].mean())


In [ ]:
 df.isnull().sum()

,0
age,0
gender,0
fever,0
cough,0
city,0
has_covid,0


In [ ]:
# df.head(1)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No


In [ ]:
## If you have categorical data , and you want to check total sub-categorical then
# we  will use df['column_name'].value_counts()

In [ ]:
df['gender'].value_counts()

,count
gender,
Female,59
Male,41


In [ ]:
### Machine --->Numbers ---->

In [ ]:
df['gender'] = df['gender'].map({"Female" : 1 , "Male" : 0})


In [ ]:
df.head(5)

,age,gender,fever,cough,city,has_covid
0,60,0,103.0,Mild,Kolkata,No
1,27,0,100.0,Mild,Delhi,Yes
2,42,0,101.0,Mild,Delhi,No
3,31,1,98.0,Mild,Kolkata,No
4,65,1,101.0,Mild,Mumbai,No


In [ ]:
df['cough'].value_counts()

,count
cough,
Mild,62
Strong,38


In [ ]:
df['cough'] = df['cough'].map({"Mild" : 0 , "Strong" : 1})
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,NaN,Kolkata,No
1,27,Male,100.0,NaN,Delhi,Yes
2,42,Male,101.0,NaN,Delhi,No
3,31,Female,98.0,NaN,Kolkata,No
4,65,Female,101.0,NaN,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,NaN,Bangalore,No
96,51,Female,101.0,NaN,Kolkata,Yes
97,20,Female,101.0,NaN,Bangalore,No
98,5,Female,98.0,NaN,Mumbai,No


In [ ]:
# df.sample(5)

,age,gender,fever,cough,city,has_covid
71,75,Female,104.0,NaN,0.0,NaN
76,80,Male,100.0,NaN,NaN,NaN
59,6,Female,104.0,NaN,NaN,NaN
14,51,Male,104.0,NaN,NaN,NaN
95,12,Female,104.0,NaN,NaN,NaN


In [ ]:
# has_covid , city

In [ ]:
df['has_covid'].value_counts()

,count
has_covid,
No,55
Yes,45


In [ ]:
df['has_covid'] = df['has_covid'].map({"Yes" : 1 , "No" : 0})
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,NaN,Kolkata,NaN
1,27,Male,100.0,NaN,Delhi,NaN
2,42,Male,101.0,NaN,Delhi,NaN
3,31,Female,98.0,NaN,Kolkata,NaN
4,65,Female,101.0,NaN,Mumbai,NaN
...,...,...,...,...,...,...
95,12,Female,104.0,NaN,Bangalore,NaN
96,51,Female,101.0,NaN,Kolkata,NaN
97,20,Female,101.0,NaN,Bangalore,NaN
98,5,Female,98.0,NaN,Mumbai,NaN


In [ ]:
df['city'].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [ ]:
df['city']=df['city'].map({"Delhi" : 0 , "Mumbai" : 1})
df.head(5)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,NaN,NaN,NaN
1,27,Male,100.0,NaN,0.0,NaN
2,42,Male,101.0,NaN,0.0,NaN
3,31,Female,98.0,NaN,NaN,NaN
4,65,Female,101.0,NaN,1.0,NaN
